[2025-06-18T12:22:55.891+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: cards_etl.etl_cards_task manual__2025-06-18T11:38:14.474255+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-06-18T12:22:55.919+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-06-18T12:22:55.921+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: cards_etl.etl_cards_task manual__2025-06-18T11:38:14.474255+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-06-18T12:22:55.935+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
